services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  mock-banco-colombia:
    image: wiremock/wiremock:3.9.0
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8081:8080"
    command:
      - "--verbose"
      - "--port=8080"

  pagos-interbancarios:
    build: .
    depends_on:
      sqlserver:
        condition: service_started
      mock-banco-colombia:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=master;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong!Passw0rd
      - MOCK_BANCO_BASE_URL=http://mock-banco-colombia:8080
    ports:
      - "8080:8080"

