apiVersion: v1
kind: Service
metadata:
  name: pagos-interbancarios
  labels:
    app: pagos-interbancarios
spec:
  selector:
    app: pagos-interbancarios
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

